[clock]
format = "15:04"

[battery]
enabled = true
hide_charging_above = 98
hide_discharging_above = 20
urgent_below = 10

[bluetooth]
enabled = true

[cpu]
enabled = true
show_above = 50
show_core_above = 95
average_seconds = 5
urgent_above = 95
